### ISSUE TITLE
Set views path

### ISSUE THREAD

**Issue by obfuscurity** [ripienaar/gdash#1]
Not sure why yet, but I had to adjust the views path when hosting it on Heroku. It wants to look in the lib/gdash directory otherwise. This worked for me but is probably not the right fix.

```
diff --git a/lib/gdash/sinatra_app.rb b/lib/gdash/sinatra_app.rb
index 05775f8..3df4a7e 100644
--- a/lib/gdash/sinatra_app.rb
+++ b/lib/gdash/sinatra_app.rb
@@ -35,6 +35,7 @@ class GDash

         set :static, true
         set :public, "public"
+        set :views, "/app/views"

         get '/' do
             erb :index
```

**Comment by ripienaar** [comment]
Seems just saying 

   set :views, "views"

was enough, I also added some other bits like a Gemfile and a placeholder for the graph templates dirs.  It now Just Works on Heroku I think :)

**Comment by obfuscurity** [comment]
Confirmed. Works for me.
