### ISSUE TITLE
Periodic internal server errors on HEAD.

### ISSUE THREAD

**Issue by blovett** [ripienaar/gdash#10]
Hi,

I'm running gdash under ubuntu (ami-ab36fbc2 specifically, in us-east-1), with apache and mod_passenger. I periodically see 500 errors. Checking the logs, I find:

[Fri Oct 28 19:09:47 2011] [error] [client 203.0.113.50] Premature end of script headers: dashboards
[ pid=5311 file=ext/apache2/Hooks.cpp:682 time=2011-10-28 19:09:47.30 ]:
  The backend application (process 27802) did not send a valid HTTP response; instead, it sent nothing at all. It is possible that it has crashed; please check whether there are crashing bugs in this application.
./lib/gdash/dashboard.rb:11: [BUG] Segmentation fault
ruby 1.8.7 (2010-01-10 patchlevel 249) [i486-linux]

[Fri Oct 28 23:49:58 2011] [error] [client 203.0.113.50] Premature end of script headers: dashboards, referer: http://gdash.example.com/dashboards/pbx/
[ pid=5312 file=ext/apache2/Hooks.cpp:682 time=2011-10-28 23:49:58.118 ]:
  The backend application (process 28268) did not send a valid HTTP response; instead, it sent nothing at all. It is possible that it has crashed; please check whether there are crashing bugs in this application.

[Sun Oct 30 06:37:01 2011] [notice] Apache/2.2.14 (Ubuntu) Phusion_Passenger/2.2.7 mod_wsgi/2.8 Python/2.6.5 configured -- resuming normal operations
/var/www/gdash/lib/gdash/../../views/layout.erb:9: [BUG] rb_gc_mark(): unknown data type 0x38(0xb757c3f0) non object
ruby 1.8.7 (2010-01-10 patchlevel 249) [i486-linux]

[Mon Oct 31 16:15:50 2011] [error] [client 203.0.113.50] Premature end of script headers: dashboards, referer: http://gdash.example.com/dashboards/pbx/
[ pid=30013 file=ext/apache2/Hooks.cpp:682 time=2011-10-31 16:15:50.912 ]:
  The backend application (process 31404) did not send a valid HTTP response; instead, it sent nothing at all. It is possible that it has crashed; please check whether there are crashing bugs in this application.

If there are any additional details I can provide, please let me know.

Thanks!

**Comment by ripienaar** [comment]
I am not sure, I guess passenger might have some additional debug you could set to get backtraces or something about the crash?

Can also try something like http://www.gittr.com/index.php/archive/logging-with-sinatra-and-passenger-another-try/ in your config.ru to get hold of stdout/stderr for instances, this might help track it down.

**Comment by blovett** [comment]
Thanks for that, ripienaar. I think it may be fixed.. I'm cautiously optimistic. I was running Sinatra from apt, which is 1.0.a. Removed that and installed using gem is giving better results. I'll close this out and re-open with more details if it reoccurs.
