### ISSUE TITLE
Apache issues "Not Found" when opening dashboard

### ISSUE THREAD

**Issue by nemros** [ripienaar/gdash#106]
Hi there, I've been struggling in the last day to configure graphite + statsd + gdash with more or less of a success.

Now I've managed to configure most things however I have a problem with gdash. I've installed it and added the necessary modules in apache. It loads up nice and put the sample you gave in the dashboards folder as well as created one of my own.

Now I can see them (with their descriptions) but whenever I click on one I get "Not Found".

Could you help me debug things and get it to work?

The config file gdash.yaml is as follows:

``` xml
:graphite: http://ec2-54-224-148-248.compute-1.amazonaws.com
:templatedir: /opt/gdash/graph_templates/dashboards
:options:
  :title: My Dashboard
  :prefix: ""
  :refresh_rate: 60
  :graph_columns: 2
  :graph_width: 500
  :graph_height: 250
  :interval_filters:
    - :label: Last Hour
      :from: -1hour
      :to: now
    - :label: Last Day
      :from: -1day
    - :label: Last Week
      :from: -1week
    - :label: Last Month
      :from: -1month
    - :label: Last Year
      :from: -1year
  :intervals:
    - [ "-1hour", "1 hour" ]
    - [ "-2hour", "2 hour" ]
    - [ "-1day", "1 day" ]
    - [ "-1month", "1 month" ]
    - [ "-1year", "1 year" ]
```

And for the demo.yaml I put a counter.graph to test it works which is as follows:

``` xml
title   "Count for Random"
area    :first
vtitle  "number"
from    "-20min"

field   :count,
    :color => "red",
    :alias => "count",
    :data => "system.loadavg_15min"
```

It uses stats generated with graphites example script.

I hope you can help and thank you in advance,
Victor

**Comment by kyzh** [comment]
I think you are pointing the  `:templatedir:` to the wrong level to start with.
Maybe what you really want is `/opt/gdash/graph_templates/` not `/opt/gdash/graph_templates/dashboards`

Then you need to have the correct directory skeleton.
If you look at the munin-graphite branch or the collectd example, here is what you one can see:

``` bash
`-- node_templates
    `-- collectd
        |-- cpu-average.graph
        |-- cpu-max.graph
        |-- dash.yaml
```

Can you provide the output of the command `tree /opt/gdash/graph_templates/`
With this, I think we might highlight missing bits or discrapency with what is required.

**Comment by nemros** [comment]
I've used the default config and adjusted it. As you suggested, by pointing to graph_templates now the dashboard is loaded properly and I no longer receive "Not found". 

Thank you very much for your prompt assistance. I hope I don't run into other problems :)
