### ISSUE TITLE
Global Config for Graphs

### ISSUE THREAD

**Issue by nstielau** [ripienaar/gdash#18]
I'm being lazy and opening an issue rather than submitting a pull request, but I didn't see a great way to do this first glance.  There is certain graph config that I'd like to be available across graphs, i.e. colors or alias' or such.  Since the .graph files are just evaluated ruby, it's easy to hack together something (I'm adding arbitrary config to the gdash.yml file, and loading in graphs), but it would be nice if this was supported out of the box.

Another thing I'd like to mention, is that Gdash does a great job of balancing load-time and view-time configuration.  I rarely need to restart the Gdash processes, just drop new graphs and updates to gdash.yml!

Here's my global config hack:

```
config = YAML.load_file("/opt/gdash/config/gdash.yaml")
field "delete_requests", :data  => "stats.api.requests.method.delete",
                                           :color => config[:colors_by_method][:"delete"]
```

**Comment by keymon** [comment]
The PR #59 is about to be merged and I think can cover this feature mixing the :graph_properties: and :include_properties:. Example in the readme in #68

**Comment by keymon** [comment]
The PR #59 has ben added. 

As described here: https://github.com/ripienaar/gdash#load-dashboard-properties-from-a-external-yaml-file- you can create a file _colors.yaml_ in the _templatesdir_ like:

  :graph_properties: 
     :colors_by_method:
       :delete: "#330000"
       :create: "#003300"

Then include the properties in the gdash.yaml in each dashboard:

  :include_properties: 
- "colors.yaml" 
- "black-theme.yml" 

and you can use it in your graph like this:

  field "delete_requests", :data  => "stats.api.requests.method.delete",
                                     :color => @properties[:colors_by_method][:delete]

Hope it works.
