### ISSUE TITLE
link 404 and dashboard not found

### ISSUE THREAD

**Issue by skeleton9** [ripienaar/gdash#29]
```
bundle exec rackup
```

This will start the application.  I'am working on Ubuntu 10.04.

```
[2012-02-27 16:59:23] INFO  WEBrick 1.3.1
[2012-02-27 16:59:23] INFO  ruby 1.8.7 (2010-01-10) [i486-linux]
[2012-02-27 16:59:28] INFO  WEBrick::HTTPServer#start: pid=15384 port=9292
```

And _127.0.0.1:9292_ shows all OK and listed the dashboard Test there.

But the links on the index page will all go 404, saying "Sinatra doesn’t know this ditty."
For example, the link of the Test dashboard will go to "127.0.0.1:9292/test"

And I tried _127.0.0.1:9292/test/count/_ to show a graph defined under test, it will say:

```
"No dashboard called count found in test/.. "
```

 I have put count.graph with dash.yaml under _graph_templates/dashboards/test/_ and set the path in the config file.
metrics.counter.test.count is a metric for testing in Graphite.

```
title   "Count for Random"
area    :first
vtitle  "number"
from    "-20min"

field   :count,
    :color => "red",
    :alias => "count",
    :data => "metrics.counter.test.count"
```

Here is the config file

```
:graphite: 127.0.0.1
:templatedir: /home/gdash/graph_templates/dashboards
#:username: admin
#:password: secret
:options:
  :title: My Dashboard
  :prefix: ""
  :refresh_rate: 60
  :graph_columns: 2
  :graph_width: 500
  :graph_height: 250
  :whisper_dir: "/var/lib/carbon/whisper"
  :intervals:
    - [ "-1hour", "1 hour" ]
    - [ "-2hour", "2 hour" ]
    - [ "-1day", "1 day" ]
    - [ "-1month", "1 month" ]
    - [ "-1year", "1 year" ]
```

**Comment by skeleton9** [comment]
seems I should write:

```
http://127.0.0.1
```

in the config file, not just 127.0.0.1

**Comment by ripienaar** [comment]
indeed, it's a url.

Did that fix it for you?

**Comment by skeleton9** [comment]
adding "http://" and now it works fine.
