### ISSUE TITLE
Add screen shots to README

### ISSUE THREAD

**Issue by narfdotpl** [ripienaar/gdash#31]
I'm about to start using Graphite. After skimming through [their docs](http://graphite.readthedocs.org/en/1.0/tools.html) in search for dashboards I opened about a dozen tabs. I don't want to install and configure all these apps just to see how they look like. Please, add screen shots to README.

**Comment by nstielau** [comment]
Hey narfdotpl, check out the demo at http://108.171.161.73:8080/ (you can demo graphite there too).  We're working on a DNS name, but that IP should work.

**Comment by narfdotpl** [comment]
@nstielau, thanks. I still think putting screen shots in the README would be nice, though. :)

**Comment by tmonk42** [comment]
I just added the sample images to the wiki page here on Github, maybe we could update the README to link to that wiki page, would that resolve this issue for you?

https://github.com/ripienaar/gdash/wiki

**Comment by narfdotpl** [comment]
Sorry it took me so long to reply. I opened a [pull request](https://github.com/ripienaar/gdash/pull/38) that reflects what I had in mind.
