### ISSUE TITLE
Unable to open dashboards.

### ISSUE THREAD

**Issue by smetj** [ripienaar/gdash#34]
Hi,

I've created a test dashboard in the dashboards directory.
The name and description of my dashboard show up on the front page.
However when I click on the link, the page can't be found...

here's the output:
# bundle exec rackup

[2012-03-22 16:57:51] INFO  WEBrick 1.3.1
[2012-03-22 16:57:51] INFO  ruby 1.8.7 (2011-06-30) [x86_64-linux]
[2012-03-22 16:57:51] INFO  WEBrick::HTTPServer#start: pid=11190 port=9292
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET / HTTP/1.1" 200 3069 0.0673
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/bootstrap-scrollspy.js HTTP/1.1" 200 2986 0.0291
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/bootstrap-popover.js HTTP/1.1" 200 2523 0.0243
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/bootstrap-dropdown.js HTTP/1.1" 200 1587 0.0228
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/bootstrap-twipsy.js HTTP/1.1" 200 7889 0.0169
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/jquery.tablesorter.min.js HTTP/1.1" 200 16520 0.0471
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /js/jquery-1.5.2.min.js HTTP/1.1" 200 85925 0.0508
10.1.15.177 - - [22/Mar/2012 16:57:58] "GET /favicon.ico HTTP/1.1" 404 462 0.0030
10.1.15.177 - - [22/Mar/2012 16:57:59] "GET /dashboards/ HTTP/1.1" 404 462 0.0022
NoMethodError - undefined method `list' for nil:NilClass:
    /opt/gdash/lib/gdash/sinatra_app.rb:128:in`GET /:category/:dash/?*'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in`compile!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `[]'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in`route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:788:in `route_eval'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in`route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:821:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in`catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:771:in`route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `each'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in`route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:886:in `dispatch!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in`call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in`catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in`call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:692:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in`call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/json_csrf.rb:17:in`call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/base.rb:47:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in`call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/nulllogger.rb:9:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/head.rb:9:in`call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/showexceptions.rb:21:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/lint.rb:48:in`_call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/lint.rb:36:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/showexceptions.rb:24:in`call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/commonlogger.rb:20:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/chunked.rb:41:in`call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/content_length.rb:14:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/handler/webrick.rb:59:in`service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
    /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
    /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:82:in`start'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/handler/webrick.rb:13:in `run'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/server.rb:265:in`start'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/lib/rack/server.rb:137:in `start'
    /usr/lib/ruby/gems/1.8/gems/rack-1.3.4/bin/rackup:4
    /usr/bin/rackup:19:in`load'
    /usr/bin/rackup:19
10.1.15.177 - - [22/Mar/2012 16:58:00] "GET /__sinatra__/404.png HTTP/1.1" 500 142167 0.3919
10.1.15.177 - - [22/Mar/2012 16:58:00] "GET /favicon.ico HTTP/1.1" 404 462 0.0038

**Comment by ripienaar** [comment]
Please show the directory layout of your graph_templates directory after first confirming it's as per the one in the README in the section "Template Directory Layout"

**Comment by smetj** [comment]
Hi,

Here's the dir layout:

``` bash
graph_templates/
├── dashboards
│   ├── cpu.graph
│   ├── dash.yaml
│   └── README.md
└── hadoopStaging
    ├── cpu.graph
    └── dash.yaml
```

**Comment by ripienaar** [comment]
So not at all like the readme then?

**Comment by smetj** [comment]
ok, I was under the assumption that one could make a deeper "drill down" folder structure.  I understand now.  I was also put offtrack because of the skewed folder tree rendering on the github webpage.  Thanks, things work now so time to build some dashboards.
