### ISSUE TITLE
Connected Line Mode

### ISSUE THREAD

**Issue by dillera** [ripienaar/gdash#40]
Hello - I see- https://github.com/ripienaar/gdash/pull/16

However, I can't get this to work. I've tried in the field and in the area section... but to no avail. Where do you put the

:connected => "true",

To get connected lines? I'm using master pulled yesterday.

field :changes, 
    :color => "red",
    :alias => "Changes",
    :connected => "true",
    :data  => "servers.log1.redis.redis_changes_since_last_save_10_180_133_62_6379.changes"

**Comment by ripienaar** [comment]
I've not had a chance to test that contributed feature, it could be that u need latest graphite? no idea, sorry :(

**Comment by dillera** [comment]
Ah ok, I know my graphite supports it, since i'm plotting it that way in the Graphite browser. I'm wondering where in your DSL for a .graph it has to be to trigger that option in the URL you pull from Graphite.

**Comment by ripienaar** [comment]
You can double check the urls gdash would generate:

<pre>
$ gem install graphite_graph
$ irb
>> require 'rubygems'
=> false
>> require 'graphite_graph'
=> true
>> GraphiteGraph.new("basic.graph").url
=> "title=Basic%20Graph&vtitle=percent&from=-1hour&width=500&height=250&until=now&areaMode=stacked&hideLegend=&target=alias(color(scale(sumSeries(derivative(mw*.munin.cpu.iowait)),0.001),%22red%22),%22IO%20Wait%22)"
</pre>


so if you know how the url should look from testing in the dashboard you can easily verify your .graph is being correctly interpreted

**Comment by dillera** [comment]
So, this just started working. It seems like it goes in the field: section, which makes sense. 

Thanks for your prompt responses- the above IRB will be useful in the future for testing!
