### ISSUE TITLE
Can't get no_alias to work

### ISSUE THREAD

**Issue by wooswiff** [ripienaar/gdash#41]
From the DSL doc I see that I should be able to use the no_alias flag to disable automatic aliasing, which I would like to use for a wildcard field.  However, I can't get this field to work.

Under the the field declaration in my .graph file, I put :no_alias => true, but this has no effect.  Maybe I just have the syntax wrong?

I see this was addressed in a recent pull request: https://github.com/ripienaar/gdash/pull/26.  If I understand this request, aliasing should be disabled by default when a wildcard is detected, but that doesn't seem to be happening for me.

**Comment by ripienaar** [comment]
are you using the gem? I dont think I pushed that code into a new gem release yet - double check its in your code

**Comment by wooswiff** [comment]
Ah, that must be it.  No I just cloned the whole project and ran it as a sinatra app.  Are there instructions for how to use it as a gem?  I guess I can figure out how to include it in a Gemfile, but from there how do I invoke gdash inside an app?

**Comment by ripienaar** [comment]
no - if you're not using the gem then you're using latest and it must be something else.

will have to investigate whats going on

**Comment by ripienaar** [comment]
please show me a sample .graph file that fails

**Comment by wooswiff** [comment]
Here's what I have.  This includes all lines that match the wildcard, but in the legend each one is just called "Page_views":

<pre>
title       "page views"
vtitle      "views"
description "Page views"

field :page_views, :scale => 1,
  :data  => "stats_counts.apps.mysite.page_loads.*.*.html.status.200",
  :no_alias => true
</pre>


Edit: added markdown tags to render the example properly.

**Comment by ripienaar** [comment]
This seems to do exactly what its supposed to do.

no_alias means gdash will not try to set any alias leaving the choice of alias entirely up to graphite and whatever other options are in effect.  Without no_alias it will try to set the alias to "page_views" here

Looking at the resulting URL this is whats happening.

**Comment by wooswiff** [comment]
When I look at the resulting URL in the graphite log, it does appear that gdash is wrapping the target in an 'alias' call, even when the no_alias flag is present.  From the same .graph file I pasted above, here is what comes up in the graphite request log:

<pre>
[29/May/2012 08:16:28] "GET /render/?title=page%20views&vtitle=views%20/%20s&from=-1hour&width=570&height=350&until=now&areaMode=none&hideLegend=false&target=alias(scale(stats_counts.apps.mysite.page_loads.*.*.html.status.200,1),%22Page_views%22) HTTP/1.1" 200 15089
</pre>


So with or without the 'no_alias' call in the .graph file, the target is getting wrapped in the alias call.  You think maybe it's graphite doing this?

For the sake of debugging, I'm happy to try a different branch or tag of gdash to narrow down the problem - is there a different one you would recommend I try?

Thanks for your help on this one.

**Comment by ripienaar** [comment]
then I can only think you're not in fact running the graphite dsl from source as you claimed.

with your .graph file:

<pre>
title "page views"
vtitle "views"
description "Page views"

field :page_views, :scale => 1, :data => "stats_counts.apps.mysite.page_loads...html.status.200", :no_alias => true
</pre>


the url gdash would produce with the latest graphite dsl from source:

<pre>
% ruby -r rubygems -r graphite_graph -e 'p GraphiteGraph.new("t.graph").url'
"title=page%20views&vtitle=views&from=-1hour&width=500&height=250&until=now&areaMode=none&target=scale(stats_counts.apps.mysite.page_loads...html.status.200,1)"
</pre>

**Comment by wooswiff** [comment]
Aha, you might have hit on it - "running the graphite dsl from source" - I don't think I took any specific steps to incorporate the latest dsl source in my project, so it sounds like this is the problem.  Things were mostly working from the getgo, so I thought it was already picking up the dsl.

This is my first time doing anything with a Sinatra app; can you tell me what I'm supposed to do to make sure I'm running the latest dsl?  Apologies if this was already in the docs somewhere and I missed it.

**Comment by ripienaar** [comment]
if you use bundler to deploy the webapp you'd just make a Gemfile with:

<pre>
source 'http://rubygems.org'
gem 'gdash'
</pre>


and you'd then create only the config and graph_templates directories in your webroot - no actual code.

and bundler will handle it all for you, when i release a new version of gdash or the dsl then you can use bundler to manage the upgrade - or prevent it from upgrading if i broke something.

**Comment by wooswiff** [comment]
Gave that a try but got the same result as before.  Here is the full output:

<pre>
% mkdir gdash_test
% cd gdash_test
% mkdir graph_templates
% mkdir config
% pico config/gdash.yml
% cat config/gdash.yml 
:graphite: http://localhost:8080
:templatedir: graph_templates
#:username: admin
#:password: secret
:options:
  :title: My Dashboard
  :prefix: ""
  :refresh_rate: 60
  :graph_columns: 2
  :graph_width: 570
  :graph_height: 350
  :whisper_dir: "/opt/graphite/storage/whisper"
  :interval_filters:
    - :label: Last Hour
      :from: -1hour
      :to: now
    - :label: Last Day
      :from: -1day
    - :label: Last Week
      :from: -1week
    - :label: Last Month
      :from: -1month
    - :label: Last Year
      :from: -1year
  :intervals:
    - [ "-1hour", "1 hour" ]
    - [ "-2hour", "2 hour" ]
    - [ "-1day", "1 day" ]
    - [ "-1month", "1 month" ]
    - [ "-1year", "1 year" ]

% pico Gemfile
% cat Gemfile 
source 'http://rubygems.org'
gem 'gdash'

% bundle install
Fetching source index for http://rubygems.org/
Using graphite_graph (0.0.2) 
Using redcarpet (2.1.1) 
Using rack (1.4.1) 
Using rack-protection (1.2.0) 
Using tilt (1.3.3) 
Using sinatra (1.3.2) 
Using gdash (0.0.2) 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
% pico t.graph
% cat t.graph 
title "page views"
vtitle "views"
description "Page views"

field :page_views, :scale => 1, :data => "stats_counts.apps.mysite.page_loads...html.status.200", :no_alias => true

% ruby -r rubygems -r graphite_graph -e 'p GraphiteGraph.new("t.graph").url'
"title=page%20views&vtitle=views&from=-1hour&width=500&height=250&until=now&areaMode=none&hideLegend=&target=alias(scale(stats_counts.apps.mysite.page_loads...html.status.200,1),%22Page_views%22)"
</pre>


Maybe an issue with one of my gem versions?

**Comment by ripienaar** [comment]
OK so now I need to do a new graphite dsl release so you'll get the new feature, but the way you have it setup now will make that easier.

will do soon.

**Comment by ripienaar** [comment]
try 'bundle update graphite_graph' that should take you up to version 0.3

**Comment by wooswiff** [comment]
Fixed!  I appreciate your help.
