### ISSUE TITLE
Different scales per time period

### ISSUE THREAD

**Issue by davewongillies** [ripienaar/gdash#48]
So I've got some metrics which are counters (eg network interface stats). To get meaningful information out of them I set the .graph for them to be :derivative => true

The problem starts when gdash renders the graph for each time period the scale shifts. I know you can get the scale for fields in a graph but is it possible to set the scale for each time period?

![Graphite graphite](http://i.imgur.com/1sL0A.png)

**Comment by ripienaar** [comment]
you can put them on different axis and different axis will have different scales.  I think thats the best graphite supports

**Comment by davewongillies** [comment]
Not sure how easy this'd be to implement but I'm thinking that this could be mitigated if gdash could be aware of the graphite storage schemas?

**Comment by ripienaar** [comment]
Would you just want to set them manually per period or something else?

**Comment by davewongillies** [comment]
Yes, being able to set scale per period is what I'm after.

**Comment by davewongillies** [comment]
I'm closing this off this ticket. Its something that I'm still after and I've got a hacked solution specific to my installation but I'll be reworking it into something that's more generally usable. I'll raise a pull request over in graphite_graph_dsl once I've got something.
