### ISSUE TITLE
Full-screen values not overriding graph definitions

### ISSUE THREAD

**Issue by obfuscurity** [ripienaar/gdash#6]
Full-screen values from the URI are not overriding height/width definitions stored in the graph configuration. The values are correct when GraphiteGraph.new is initialized (i.e. @properties is correct in GraphiteGraph.load_graph) but are getting "lost" in GraphiteGraph.url when constructing url_parts.

I'm sure I'm overlooking something stupid but I haven't been able to track down where it's leaking.

**Comment by ripienaar** [comment]
fixed in 6910e89cfc2ca9549fa64bfc34d74b3f724edd7e hopefully
