### ISSUE TITLE
support multiple graphite backends

### ISSUE THREAD

**Issue by falkenbt** [ripienaar/gdash#60]
Hi, 

what would need to be changed in order to allow overwriting of the graphite host that is currently being defined in /config/gdash.yaml? 

As result I would like to be able to define the graphite host in the dashboard definition. 

Thanks
Thomas

**Comment by ripienaar** [comment]
i think it would be quite easy really, on the road at the moment for the next week or two - if u want to take a stab at it that'd be awesome

**Comment by falkenbt** [comment]
I gave it a shot:
https://github.com/ripienaar/gdash/pull/61

**Comment by falkenbt** [comment]
now without the other commits. 
https://github.com/ripienaar/gdash/pull/62

**Comment by blufor** [comment]
hey @falkenbt, i'd suggest you try to stitch two carbon-caches with carbon-relay and serve that over single api endpoint. ymmv :]

**Comment by falkenbt** [comment]
That sounds like more work :) The above solutions works well for me. 
Our use case: multiple graphite installations in currently two different datacenters (more to come) with some sharing the same metric names. I would like to keep them seperated.
