### ISSUE TITLE
Thanks for providing inspiration

### ISSUE THREAD

**Issue by gingerlime** [ripienaar/gdash#63]
Just a quick note to say thanks for GDash. I haven't used it much, but some of its design and ideas provided inspiration to a new graphite dashboard just released called [giraffe](https://github.com/kenhub/giraffe) - also available on github as an open source project.

Would be great to collaborate somehow for the benefit of the graphite community.

**Comment by ripienaar** [comment]
nice one :) more the merrier, I sent you some twitter shoutout :)

**Comment by gingerlime** [comment]
Cheers. Much appreciated.

**Comment by chjohnst** [comment]
:+1:

**Comment by bwhaley** [comment]
+1

@gingerlime Did you happen to notice issue #84? It's basically suggesting the same thing - giraffe like functionality in gdash.

**Comment by blufor** [comment]
this kind of involves a vision of mine (still no time for that :[) of making a fork of gdash with graphs generated from json data by the awesome easy-to-use rickshaw library (http://code.shutterstock.com/rickshaw/)... would be dfntly cheaper on my backends and thus possibly faster ;]
