### ISSUE TITLE
Provide a default collectd dashboard

### ISSUE THREAD

**Issue by kyzh** [ripienaar/gdash#87]
I really liked the fact that there is a branch with a default dashboard with data comming from munin.
I now use collectd and i think that a collectd topic branch would be nice to have too

**Comment by keymon** [comment]
We use collectd and I got a dashboard with several OS metrics. I will try to upload as I got some time.

**Comment by kyzh** [comment]
I just did a pull request #88 
I didn't realised it will create another issue.
Feel free to edit/comment/improve the dashboard i proposed.

**Comment by keymon** [comment]
Maybe we can create some kind of dashboard gallery or similar, outside of the base code. Not sure how, maybe just a new git repository with the templates.

**Comment by falkenbt** [comment]
Should have looked here first, I already merged it, sorry. 
But anyhow as long as there is such a limited number of templates I think it's a good idea to have them here to help beginners - it sure would have helped me when I started gdash. 
When the number grows, we can think about a seperate repo. What do you think?

**Comment by keymon** [comment]
Yeah, you are right. Makes no sense keep it blocked. If he number grows, we can split it. Thx!
