### ISSUE TITLE
whisper_dir

### ISSUE THREAD

**Issue by hamann** [ripienaar/gdash#91]
```
:whisper_dir: "/var/lib/carbon/whisper"
```

Is this necessary and used somewhere in the code? I can run gdash local with graphs from another graphite host. In case it isn't, I think it should be removed from configuration to not confuse users (at first I thought it has to be installed on the graphite host because of this)

**Comment by keymon** [comment]
I don't think is used at all

  $ grep -R whisper_dir *
  config/gdash.yaml-sample:  :whisper_dir: "/var/lib/carbon/whisper"
  lib/gdash/sinatra_app.rb:      @whisper_dir = options.delete(:whisper_dir) || "/var/lib/carbon/whisper"

**Comment by falkenbt** [comment]
I removed it: ca7d7f26bc83e0bbc3df00d5f9c965c2d8dff75e
