### ISSUE TITLE
Detailed view - graph size

### ISSUE THREAD

**Issue by toerkl** [ripienaar/gdash#93]
Hi,

Is there an easy way to set a different height and width of the graphs in the detailed view, i.e. after you have clicked on one of the graphs on a dashboard? I would like to have them bigger there if possible.

T

**Comment by falkenbt** [comment]
I just realized that after switching to bootstrap thumbnails (https://github.com/ripienaar/gdash/pull/86) I can't figure out how to adjust the image size in all views. 
Any ideas?

**Comment by bwhaley** [comment]
Potential fix for this in bwhaley/gdash@4f4bfb7. Have not opened a PR yet. @lindqt01 @falkenbt Would you be willing to test out that commit?

**Comment by toerkl** [comment]
@bwhaley happy to try it but now sure how to do it.

**Comment by falkenbt** [comment]
@bwhaley I tested it, looks good. Can you send a pull request?

**Comment by toerkl** [comment]
Works like a charm! Thanks! Sorry, one last question. How do I specify a different size in the detailed view. Might want to have smaller thumbnail-like images on the dashboard and then bigger when clicking on a graph.

**Comment by bwhaley** [comment]
You can use `?width=xxx&height=yyy` in the query parameters to change the size in any view.

**Comment by bwhaley** [comment]
Does this answer your questions @lindqt01 ?

**Comment by toerkl** [comment]
@bwhaley sorry a bit slow sometimes, thanks for the response. Do you put that in the URL then, in the browser, or somewhere else?

**Comment by bwhaley** [comment]
yes, in the URL. for example

```
http://gdash.example.com/my/dashboard/time/-1month/now?height=500&width=800
```

Or

```
http://gdash.example.com/my/dashboard/details/cpu/?height=500&width=800
```

**Comment by toerkl** [comment]
@bwhaley thanks a lot for your help.
